-- GENERATE A SELECT COLUMN LIST THAT HAS ALL BLANK VALUES FOR EVERY COLUMN IN THE TABLE
-- USE AS A STARTING POINT FOR GENERATING TEST DATA

-- SET QUERY RESULTS TO TEXT

DECLARE @TABLE_NAME	VARCHAR(50) = 'tablename_goes_here';

SELECT ', REPLICATE(' + '''' + ' ' + '''' + ', ' + CONVERT(VARCHAR(5), CHARACTER_MAXIMUM_LENGTH) + ')'
 + ' -- ' + COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = @TABLE_NAME
ORDER BY ORDINAL_POSITION
