SELECT 
	COLUMN_NAME
,	LAG(CHARACTER_MAXIMUM_LENGTH, 1, 0) OVER (ORDER BY ORDINAL_POSITION) + 1 START_POSITION
,	CHARACTER_MAXIMUM_LENGTH [LENGTH]
,	LAG(CHARACTER_MAXIMUM_LENGTH, 1, 0) OVER (ORDER BY ORDINAL_POSITION) + CHARACTER_MAXIMUM_LENGTH + 1 END_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schema-goes-here'
AND TABLE_NAME = 'table-name-goes-here'
ORDER BY ORDINAL_POSITION
