;WITH CTE AS (
	SELECT 
 		ORDINAL_POSITION
	,	COLUMN_NAME
	,	SUM(CHARACTER_MAXIMUM_LENGTH) OVER (ORDER BY ORDINAL_POSITION) TOTAL_LENGTH
	,	CHARACTER_MAXIMUM_LENGTH [LENGTH]
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_SCHEMA = 'schema-name-goes-here'
	AND TABLE_NAME = 'table-name-goes-here'
)

SELECT 
 	ORDINAL_POSITION
,	COLUMN_NAME
,	LAG(TOTAL_LENGTH, 1, 0) OVER (ORDER BY ORDINAL_POSITION) + 1 START_POSITION
,	[LENGTH]
,	TOTAL_LENGTH END_POSITION
FROM CTE
ORDER BY ORDINAL_POSITION
