;WITH CTE AS (
	SELECT 
 		ORDINAL_POSITION
	,	COLUMN_NAME
	,	LAG(CHARACTER_MAXIMUM_LENGTH, 1, 0) OVER (ORDER BY ORDINAL_POSITION) 
			+ CASE WHEN ORDINAL_POSITION = 1 THEN 0 ELSE CHARACTER_MAXIMUM_LENGTH END [OFFSET]
	,	CHARACTER_MAXIMUM_LENGTH [LENGTH]
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_SCHEMA = 'schema-name-goes-here'
	AND TABLE_NAME = 'table-name-goes-here'
)

SELECT 
 	ORDINAL_POSITION
,	COLUMN_NAME
,	OFFSET + 1 START_POSITION
,	[LENGTH]
,	OFFSET + 1 + [LENGTH] END_POSITION
FROM CTE
ORDER BY ORDINAL_POSITION
